
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace/backend
      - ./api/backend/app:/workspace/backend/app
    environment:
      - DATABASE_URL=sqlite:///backend/placement_scheduler.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/workspace
      - /workspace/node_modules
    depends_on:
      - backend
